sahidcholayil/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls',namespace='web')),
    
    path('tinymce/', include('tinymce.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Sahid Cholayil Administration"
admin.site.site_title = "Sahid Cholayil Admin Portal"
admin.site.index_title = "Welcome to Sahid Cholayil Admin Portal"

web/urls.py
from django.urls import path
from .import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('updates', views.updates, name='updates'),
    path('gallery', views.gallery, name='gallery'),
    path('position', views.position, name='position'),
    path('awards', views.awards, name='awards'),
    path('contact', views.contact, name='contact'),
]

web/models.py
from django.db import models
from django.db.models.fields import DateField, EmailField
from versatileimagefield.fields import VersatileImageField


class Update(models.Model):
    title = models.CharField(max_length=100)
    image = VersatileImageField(upload_to='update')
    details = models.TextField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)

    def __str__(self):
        return str(self.title)


class Gallery(models.Model):
    title = models.CharField(max_length=100)
    image = VersatileImageField(upload_to='gallery')

    def __str__(self):
        return str(self.title)


class Position(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.title)


class Award(models.Model):
    title = models.CharField(max_length=100)
    image = VersatileImageField(upload_to='award')
    subject = models.CharField(max_length=100)
    date = DateField(blank=True, null=True)
    place = models.CharField(max_length=100)

    def __str__(self):
        return str(self.title)


TIME_CHOICES = (
    ('09300950', '9:30 am - 9:50 am'),
    ('10001020', '10:00 am - 10:20 am'),
    ('10301050', '10:30 am - 10:50 am'),
)

class Contact(models.Model):
    name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    whatsapp_number = models.CharField(max_length=100)
    time = models.CharField(max_length=128,choices=TIME_CHOICES)
    email = EmailField(max_length=100)
    date = models.CharField(max_length=100)
    

    def __str__(self):
        return str(self.name)

web/forms.py
from django import forms
from .models import Contact
from django.forms.widgets import Select, TextInput


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Name'}),
            'subject': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Subject'}),
            'location': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Location'}),
            'email': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Email'}),
            'number': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Phone Number'}),
            'whatsapp_number': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Whatsapp Number'}),
            'date': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Date'}),
            'time': Select(attrs={'class': 'required form-control select', 'placeholder': 'Time'}),
        }

web/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Award, Gallery, Position, Update
from .forms import ContactForm
import json


def index(request):
    updates = Update.objects.filter().order_by('-id')[:6]
    gallery = Gallery.objects.filter().order_by('-id')[:8]
    context = {
        'updates': updates,
        'gallery': gallery
    }
    return render(request, 'web/index.html', context)


def about(request):
    return render(request, 'web/about.html')


def updates(request):
    updates = Update.objects.all()
    context = {
        'updates': updates
    }
    return render(request, 'web/updates.html', context)


def gallery(request):
    gallery = Gallery.objects.all()
    context = {
        'gallery': gallery
    }
    return render(request, 'web/gallery.html', context)


def position(request):
    position = Position.objects.all()
    context = {
        'position': position
    }
    return render(request, 'web/position.html', context)


def awards(request):
    award = Award.objects.all()
    context = {
        'award': award
    }
    return render(request, 'web/awards.html', context)


def contact(request):
    contact = ContactForm(request.POST or None)
    if request.method == 'POST':
        if contact.is_valid():
            data = contact.save(commit=False)
            data.save()
            response_data = {
                "status": "true",
                "title": "Submited",
                "message": "Thank you for getting in touch!"
            }
        else:
            print(contact.errors)
            response_data = {
                "status": "false",
                "title": "Form validation error",
            }
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    context = {
        'contact': contact,
    }
    return render(request, 'web/contact.html', context)

templates/partials/footer.html
{% load static %}

<hr color="#fff" id="hrline" />

<footer class="footer" id="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-6 col-md-6" id="useful">
        <h4>USEFUL LINKS</h4>
        <ul class="list-unstyled d-flex" id="sm_title">
          <li><a href="{% url 'web:index' %}">Home</a></li>
          <li><a href="{% url 'web:about' %}">About</a></li>
          <li><a href="{% url 'web:awards' %}">Awards</a></li>
        </ul>
        <ul class="list-unstyled d-flex" id="sm_title">
          <li><a href="{% url 'web:gallery' %}">Gallery</a></li>
          <li><a href="{% url 'web:updates' %}">Updates</a></li>
          <li><a href="{% url 'web:contact' %}">Contact</a></li>
        </ul>
      </div>
      <div class="col-lg-4 col-sm-6 col-md-6" id="footer_contact">
        <h4 id="fot_con_title">QUICK CONTACT</h4>
        <p>Harvard Square</p>
        <p>82 Wendell Ave.STE 100</p>
        <p>Pittsfield, Massachusetts 01201</p>
      </div>
      <div class="col-lg-4 col-sm-6 col-md-6">
        <h4 class="mb-4">CONNECT</h4>
        <ul class="list-unstyled d-flex" id="media">
          <li><a href="#" class="fa fa-linkedin"></a></li>
          <li><a href="#" class="fa fa-twitter"></a></li>
          <li><a href="#" class="fa fa-instagram"></a></li>
          <li><a href="#" class="fa fa-facebook"></a></li>
          <li><a href="#" class="fa fa-youtube"></a></li>
        </ul>
      </div>
    </div>

    <p id="copyright" style="color: grey">Copyright © SahidCholayil, All Rights Reserved.Developed by <a href="https://gedexo.com/" target="blank" style="color: #c4a34e"> Gedexo</a></p>
  </div>
</footer>

templates/partials/header.html
{% load static %}
<div class="header">
    <div class="container">
        <div class="row justify-content-between align-items-center" id="headerall">
            <div class="col-lg-3 col-md-5 col-sm-5">
                <a class="navbar-brand img-fluid" href="{% url 'web:index' %}">
                    <img src="{% static 'web/img/logo.png' %}" alt="" class="logo">
                </a>
            </div>
            <div class="col-lg-9 col-md-2 col-sm-2 d-none d-lg-block">
                <nav class="my-nav navbar navbar-light navbar-expand-lg">

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item" id="nav-lap">
                            <a class="nav-link menu" href="{% url 'web:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link menu" href="{% url 'web:about' %}">About</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link menu" href="{% url 'web:updates' %}">Updates</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link menu" href="{% url 'web:gallery' %}">Gallery</a>

                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link menu" href="{% url 'web:position' %}">Position</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link menu" href="{% url 'web:awards' %}">Awards</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link menu" href="{% url 'web:contact' %}" style="border: none;">Contact</a>
                        </li>

                    </ul>

                </nav>
            </div>
        </div>
    </div>
        <div class="d-lg-none">
    <div id="mobile_menu_wrapper" class="">
         <!-- add active class for mobile menu -->
        <div id="mobile_menu">
            <span id="menu_toggler"></span>
        </div>
        <div class="full_window"> 
           <ul style="list-style: none;" >
               <li><a href="{% url 'web:index' %}">Home</a></li>
               <li><a href="{% url 'web:about' %}">About</a></li>
               <li><a href="{% url 'web:updates' %}">Updates</a></li>
               <li><a href="{% url 'web:gallery' %}">Gallery</a></li>
               <li><a href="{% url 'web:position' %}">Position</a></li>
               <li><a href="{% url 'web:awards' %}">Awards</a></li>
               <li><a href="{% url 'web:contact' %}">Contact</a></li>
           </ul>
        </div>
    </div>
</div>

</div>

templates/web/about.html
{% extends 'web/base.html' %} {% load static %} {% block content %}

<!-- Home -->
<section class="banner-content">
  <div class="container-fluid">
    <div class="title">
      <div class="row" id="heading">
        <h1>About</h1>
      </div>
    </div>
    <div class="about" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <img src="{% static 'web/img/news2.png' %}" />
            <p id="about_head">
              Sahid Cholayil is an Indian entrepreneur from Dubai, the founder
              and chairman of “Mission 3G”, and the winner of 2018
              Entrepreneurship RACE Award Competition at Harvard University.
            </p>
            <p>
              Mission 3G is a humanitarian enterprise founded by Dr Sahid as a
              result of years of research in multiple areas such as threats to
              mankind, society & nation, education, technology, neuroscience,
              psychology, sociology, epistemological elements of philosophy,
              world economics – market needs and feasibility, and value systems.
              Mission 3G is led by a team of academic experts from Harvard
              University, Massachusetts Institute of Technology, Indian
              Institute of Technology (Bombay), Indian Institute of Management
              (Bangalore) and many other institutes of academic excellence. The
              organization is addressing various problems of third millennium
              such as existential vacuum of human life, challenges of education
              3.0, technology unemployment due to fourth industrial revolution
              etc and there by developing solutions to impact humanity by means
              of human centric designs and naturalistic thinking. Dr Sahid and
              his team is well-known for their work towards developing the
              world’s first “Life Management System” that can deliver
              individualized dynamic curriculum and personalized dynamic
              pedagogy which will be catering to the learning needs of an
              individual from “Womb to Tomb”. The concept of “Life Management
              System” has evolved from Sahid’s vision to help every human life
              identify the true purpose of their lives through an educational
              paradigm and further helping humanity to pursue their purpose. The
              Life Management System is in an innovative venture administering
              the latest technology of IBM WATSON and SAP HANA, operating
              through 3G Learning Initiatives (Bangalore) and 3G Institute of
              Research and Policy Studies (New Delhi).
            </p>
            <p>
              Mission 3G team under the leadership of Dr Sahid is also actively
              engaged in bridging gap between learners and phygital learning
              solutions in India. On 26th January 2018, Dr. Sahid has announced
              the “Mission 3G” national campaign at Indian School of Business in
              Hyderabad which intends to accelerate the digitization of learning
              in India. The Mission 3G “Build India to Serve the World” campaign
              is the initiative laid out to address the technology unemployment
              in India with a vision to leverage India’s demographic dividend
              and developing sustainable entrepreneurial ecosystem for small
              medium enterprises. The ongoing campaign has gained quite a
              momentum with the leading Ed-tech Indian entrepreneurs joining
              hands together for this national cause first-time ever. The global
              campaign of Mission 3G was launched at Harvard University on
              February 8th 2018 which received significant support of industry
              thought leaders and educationists across the globe
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/web/awards.html
{% extends 'web/base.html' %} {% load static %} {% block content %}

    <section class="banner-content">
        <div class="container-fluid">
            <div class="title mb-5">
                <div class="row" id="heading">
                  <h1>Awards</h1>
                </div>
              </div>
        <div class="awards mt-5"  id="awards">
            <div class="container">
                <div class="row">

                    {% for award in award %}
                    <div class="col-lg-6 col-sm-12 col-md-12">
                        <img src="{{award.image.crop.540x240}}" alt="">  
                        <div class="award">
                        <h4 style="color: #c4a34e;">{{award.date|date:"Y"}}<h4>
                        <p>{{award.title}}</p>
                       <p>{{award.subject}}</p>  
                        <p>{{award.place}}</p>
                    </div>
                </div> 
                    {% endfor %}
            </div>
        </div>   
        </div>
        </div>
    </section>



{% endblock %}

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sahid Cholayil</title>

    <meta property="og:title" content="Sahid Cholayil" />
    <meta property="og:description" content="Sahid Cholayil is an Indian entrepreneur from Dubai, the founder and chairman of “Mission 3G”, and the winner of 2018 Entrepreneurship RACE Award Competition at Harvard University" />
    <meta property="og:image" content="{% static 'web/img/news2.png' %}" />

    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link rel="stylesheet" href="{% static 'web/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'web/css/lightbox.min.css' %}" />
    <link rel="stylesheet" href="{% static 'web/vendor/icofont/icofont.min.css' %}" />
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'web/css/responsive.css' %}" />
    <link rel="icon" type="image/x-icon" href="{% static 'web/img/news2.png' %}" style="border-radius: 50%;" />
    
    
  </head>

  <body>
    {% include "partials/header.html" %} 
    {% block content %}
    
    {% endblock %} 
    {% include "partials/footer.html" %}

    <script src="{% static 'web/js/jquery.min.js' %}"></script>
    <script src="{% static 'web/js/popper.min.js' %}"></script>
    <script src="{% static 'web/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'web/js/script.js' %}"></script>
    <script src="{% static 'web/js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

templates/web/blogs.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

{% endblock %}

templates/web/contact.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

<section class="banner-content">
  <div class="container-fluid">
    <div class="title mb-5">
      <div class="row" id="heading">
        <h1>Contact</h1>
      </div>
    </div>
    <section class="contact" id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-sm-12 col-md-6" id="contact-adrs">
            <h4 class="pb-4" style="color: #c4a34e">Get In Touch</h4>
            <p>Harvard Square</p>
            <p>82 Wendell Ave.STE 100</p>
            <p>Pittsfield, Massachusetts 01201</p>
            <p>Tel (Office):<a href="tel:+97112345645"> 97112345645</a></p>
            <p>Direct :<a href="tel:+971123456456"> 971123456456</a></p>
            <p>Email : <a href="#">ShaidCholayil@gmail.com</a></p>
          </div>

          <div class="col-lg-6 col-sm-12 col-md-6" id="contactbg">
            <h4 style="color: #c4a34e">Get An Appoinment</h4>
            <div class="row">
              <div class="col-12">
                <form id="contact-form" method="POST" action="" class="ajax">
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-12"> <div class="form-group" > {{contact.name}}</div></div>
                    <div class="col-12"> <div class="form-group" > {{contact.subject}}</div></div>
                    <div class="col-6"> <div class="form-group" > {{contact.location}}</div></div>
                    <div class="col-6"><div class="form-group" > {{contact.email}}</div></div>
                    <div class="col-6"> <div class="form-group" > {{contact.number}}</div></div>
                    <div class="col-6"> <div class="form-group" > {{contact.whatsapp_number}}</div></div>
                    <div class="col-6"><div class="form-group" > {{contact.date}}</div></div>
                    <div class="col-6"> <div class="form-group" > {{contact.time}}</div></div>
                  </div>
                  <button
                    class="btn btn-primary"
                    id="contact-btn"
                    type="submit"
                  >
                    Submit
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</section>

{% endblock %}

templates/web/gallery.html
{% extends 'web/base.html' %} {% load static %} {% block content %}

<section class="banner-content">
  <div class="container-fluid">
    <div class="title mb-5">
      <div class="row" id="heading">
        <h1>Gallery</h1>
      </div>
    </div>

    <section class="gallery" id="gallery1">
      <div class="container">
        <div class="row">
          {% for gallery in gallery %}

          <div class="col-lg-4 col-sm-6 col-md-6">
            <a
              href="{{gallery.image.url}}"
              data-lightbox="roadtrip"
              target="blank"
            >
              <img src="{{gallery.image.crop.350x230}}" alt="Gallery" />
            </a>
          </div>

          {% endfor %}
        </div>
      </div>
    </section>
  </div>
</section>

<!-- ********Footer******** -->

{% endblock %}

templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}


<!-- Home -->
<section class="banner-content">
    <div class="container">
        <div class="banner">
            <div class="row banner " id="banner_img">
                <!-- <div class="bordered-box"> -->
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 margin-margin  bordered-box">
                   <div class="row">
                        <!-- <div id="banner_title">
                            <p>Products or Services.</p>
                            <p>it's all about people.</p>
                            <div class="banner_name">
                                <h1>Dr sahid cholayil </h1>
                                <p id="sahid_company">Founder & Chairman at GENIUS GROUP</p>
                            </div>
                        </div> -->

                        <div class="col-lg-6 col-md-6 col-sm-6 col-6" style="background-color: rgb(48, 48, 48);text-align: center;">
                            <img src="../../static/web/img/logo.png" alt="" srcset="" class="logo logo-responsive">
                            <div class="servent-class">
                                <h4 class="servent">Servent of Humanity</h4>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-6">
                            <ul class="list-none">
                                <li>HUMANITARIAN</li>
                                <li>EGALITARIAN</li>
                                <li>VISIONARY</li>
                                <li>DREAMER & TRANSFORMER</li>
                                <li>THINKER & DOER</li>
                                <li>SOCIAL ENTREPRENEUR</li>
                                <li>LEADER & FOUNDER</li>
                            </ul>
                        </div>
                    </div>
                    <div>
                        <h3 class="mission">MISSION POSSIBLE</h3>
                    </div>
                </div>
                


                <div class="col-lg-6 col-md-6 col-sm-12 col-12 d-sm-block d-block text-right">
                    <img class="sahidimg" src="{% static 'web/img/Sahid.png' %}" alt="DR SAHID">
                </div>
            </div>
        </div>
        <!-- </div> -->
    </div>
</section>

<!-- About -->
<section class="about" id="about">
    <div class="container">
        <h2 class="">About</h2>
        <p id="about_head">Sahid Cholayil is an Indian entrepreneur from Dubai, the founder and chairman of “Mission
            3G”, and the winner of 2018 Entrepreneurship RACE Award Competition at Harvard University.</p>
        <p>Mission 3G is a humanitarian enterprise founded by Dr Sahid as a result of years of research in multiple
            areas such as threats to mankind, society & nation, education, technology, neuroscience, psychology,
            sociology, epistemological elements of philosophy, world economics – market needs and feasibility, and
            value systems. Mission 3G is led by a team of academic experts from Harvard University, Massachusetts
            Institute of Technology, Indian Institute of Technology (Bombay), Indian Institute of Management
            (Bangalore) and many other institutes of academic excellence. The organization is addressing various
            problems of third millennium such as existential vacuum of human life, challenges of education 3.0,
            technology unemployment due to fourth industrial revolution etc and there by developing solutions to
            impact humanity by means of human centric designs and naturalistic thinking. Dr Sahid and his team is
            well-known for their work towards developing the world’s first “Life Management System” that can deliver
            individualized dynamic curriculum and personalized dynamic pedagogy which will be catering to the
            learning needs of an individual from “Womb to Tomb”. The concept of “Life Management System” has evolved
            from Sahid’s vision to help every human life identify the true purpose of their lives through an
            in an innovative venture administering the latest technology of IBM WATSON and SAP HANA, operating
            educational paradigm and further helping humanity to pursue their purpose. The Life Management System is
            through 3G Learning Initiatives (Bangalore) and 3G Institute of Research and Policy Studies (New Delhi).
        </p>
        <button class="btn"><a href="{% url 'web:about' %}">More About</a></button>
        <button class="btn"><a href="{% url 'web:contact' %}">Get Appointment</a></button>
    </div>
    </div>
</section>

<!-- News and Updates -->
<section class="news" id="news">
    <div class="container">
        <h2>News and Updates</h2>
        <div class="row" id="newsrd">
            {% for updates in updates %}
            <div class="col-lg-4 col-sm-6 col-md-6">
                <img src="{{updates.image.crop.350x240}}" alt="">
                <p>{{updates.details}}</p>
                <p id="date">{{updates.date}}<span> <a style="text-decoration: none; color: #c4a34e ; "
                            href="{% url 'web:updates' %}">Read More...</a></span> </p>

            </div>
            {% endfor %}
        </div>
    </div>
    </div>
</section>

<!-- Gallery -->
<section class="gallery" id="gallery1">
    <div class="container">
        <h2>Gallery</h2>
        <div class="row">
            {% for gallery in gallery %}
            <div class="col-lg-3 col-md-6 col-sm-6 ">
                <a href="{{gallery.image.url}}" data-lightbox="roadtrip" target="blank">
                    <img src="{{gallery.image.crop.350x230}}" alt="Gallery">
                </a>
            </div>
            {% endfor %}


            <div class="col-12 text-center">
                <button class="btn" id="gallerybtn"> <a href="{% url 'web:gallery' %}">Explore More</a> </button>
            </div>
        </div>
    </div>
</section>


<!-- ********Footer******** -->









{% endblock %}

templates/web/partials/team-section.html
{% load static %}
<div class="team-section container-fluid no-padding">
    <div class="section-padding"></div>
    <div class="container">
        <div class="row">
            <!-- Main Carousel -->
            <div id="main-carousel1" class="carousel slide carousel-fade" data-ride="carousel">
                <div role="listbox" class="carousel-inner">
                    <div class="item active">
                        <div class="team-content">
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <img src="{% static 'web/images/team.png' %}" alt="team" width="468" height="595" />
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <div class="section-header left-header">
                                    <h3>Our Expertise</h3>
                                    <h5>High Quality and Tasty</h5>
                                    <img src="{% static 'web/images/section-seprator-1.png' %}" alt="section-seprator" width="70" height="3">
                                    <p>
                                        Leechoco is specialized in made-to-order confectionery products. We carry a large
                                        selection of premium cakes, chocolates, pies, and a wide variety of pastries and
                                        other delicatessens.
                                    </p>
                                    <div class="team-contact-info">
                                        
                                        <p><a href="mailto:{{about.email}}" title="{{about.email}}"><i class="fa fa-envelope" aria-hidden="true"></i>{{about.email}}</a></p>
                                        <p><a href="tel:{{about.phone}}" title="{{about.phone}}"><i class="fa fa-phone" aria-hidden="true"></i>Phone: {{about.phone}}</a></p>
                                    </div>
                                </div><!-- Section Header /-  -->
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- Main Carousel /-  -->
        </div>
    </div><!-- Container /- -->
</div><!-- Team Section /- -->

templates/web/position.html
{% extends 'web/base.html' %} {% load static %} {% block content %}

    <section class="banner-content">
        <div class="container-fluid">
            

            <div class="title mb-5">
                <div class="row" id="heading">
                  <h1>Position</h1>
                </div>
              </div>

        <div class="position mt-5"  id="position">
            <div class="container pl-5">
                <div class="row">

                    {% for position in position %}
                    <div class="col-lg-7">                        
                        <h4>{{position.title}}</h4>
                        <p>{{position.details}}</p>
                    </div>   
                    {% endfor %}             
                    
                </div>               
                
                
            </div>
        </div>

        
            
        </div>
        </div>
    </section>


{% endblock %}

templates/web/products.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

{% endblock %}

templates/web/services.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

{% endblock %}

templates/web/single_blog.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

{% endblock %}